services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Bnf\MfaWebauthn\:
    resource: '../Classes/*'

  Bnf\MfaWebauthn\Provider\WebAuthnProvider:
    tags:
      - name: mfa.provider
        identifier: 'webauthn'
        title: 'Security Keys'
        description: 'Security keys are hardware devices containing cryptographic keys. They can be used for two-factor authentication. Security keys must support the Webauthn standard by implemented FIDO2 or U2F interfaces.'
        setupInstructions: 'Do you have your security key? To register a security key insert it into the USB port and press Next. When it starts flashing, press the gold disc on it.'
        icon: 'tx-mfawebauthn-key'
        defaultProviderAllowed: true
        before: 'recovery-codes,hotp,totp'
