services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Bnf\MfaWebauthn\:
    resource: '../Classes/*'

  mfa.webauthn.token.provider:
    class: Bnf\MfaWebauthn\Provider\WebAuthnProvider
    arguments:
      $userVerification: !php/const Webauthn\AuthenticatorSelectionCriteria::USER_VERIFICATION_REQUIREMENT_DISCOURAGED
      $authenticatorAttachment: !php/const Webauthn\AuthenticatorSelectionCriteria::AUTHENTICATOR_ATTACHMENT_CROSS_PLATFORM
    tags:
      - name: mfa.provider
        identifier: 'webauthn'
        title: 'Security Keys'
        description: 'Security keys are hardware devices containing cryptographic keys. They can be used for two-factor authentication. Security keys must support the Webauthn standard by implemented FIDO2 or U2F interfaces.'
        setupInstructions: 'Do you have your security key? To register a security key insert it into the USB port and press Next. When it starts flashing, press the gold disc on it.'
        icon: 'tx-mfawebauthn-key'
        defaultProviderAllowed: true
        before: 'recovery-codes,hotp,totp'

  mfa.webauthn.platform.provider:
    class: Bnf\MfaWebauthn\Provider\WebAuthnProvider
    arguments:
      $userVerification: !php/const Webauthn\AuthenticatorSelectionCriteria::USER_VERIFICATION_REQUIREMENT_PREFERRED
      $authenticatorAttachment: !php/const Webauthn\AuthenticatorSelectionCriteria::AUTHENTICATOR_ATTACHMENT_PLATFORM
    tags:
      - name: mfa.provider
        identifier: 'webauthn-platform'
        title: 'Built-in Authenticators'
        description: 'Internal authenticators are second factors built into notebooks or mobile phones via a trusted platform module and a fingerprint sensor.'
        icon: 'tx-mfawebauthn-fingerprint'
        defaultProviderAllowed: true
        before: 'recovery-codes,hotp,totp'
        after: 'webauthn'
